export const intelligenceManageHeaderTable=[
    {slot: 'radio' },
    {slot: 'userNumber' },
    {slot: 'userName' },
    {slot: 'zhengshuh' },
    {slot: 'zzmc' },
    {slot: 'zzlx' },
    {slot: 'bfrq' },
    {slot: 'bfdw' },
    {slot: 'syyw' },
    {slot: 'sxrqone' },
    {slot: 'sxrqtwo' },
    {slot: 'glxx' },
];
export const intelligenceManageTable=[
    {slot: 'radio' },
    { prop: 'content', label: '员工编号', align: 'center' },
    { prop: 'deptName', label: '员工姓名', align: 'center' },
    { prop: 'assetsNumber', label: '资质证书号', align: 'center' },
    { prop: 'workCategoryName', label: '资质名称', align: 'center',},
    { prop: 'workName', label: '资质类型', align: 'center' },
    { prop: 'workName', label: '颁发日期', align: 'center' },
    { prop: 'workName', label: '颁发单位', align: 'center' },
    { prop: 'workName', label: '适用业务', align: 'center' },
    { prop: 'workName', label: '生效日期', align: 'center' },
    { prop: 'workName', label: '失效日期', align: 'center' },
    {slot: 'relationInfo' },
];
